### ISSUE TITLE
Prevent generation of extra properties

### ISSUE THREAD

**Issue by rhullah** [molnarg/generate.js#3]
While using `generate.js` with a `js-schema`, sometimes it generates objects with extra properties not defined in the schema.  I know that even with the extra properties the object still technically validates against the schema.  But it would be nice if we could tell `generate.js` not to create unspecified properties.

**Comment by molnarg** [comment]
Yeah, this default behavious is intentional. Try `'*': null`, it should work fine for you use-case. Example:

```
var Color = Array.of(3, Number.min(0).max(1));

var Duck = schema({
  quack : Function,
  age   : [0, 1, 2, 3, 4, 5, "very old"],
  color : Color,
  '*': null
})
```

**Comment by rhullah** [comment]
I was wondering if that's what I needed to do.  I just didn't know if it would still generate the random null properties.  Thanks for the info.
