### ISSUE TITLE
re-purpose the lib?

### ISSUE THREAD

**Issue by jonschlinkert** [molnarg/generate.js#4]
I have the org, https://github.com/orgs/generate, and I'm creating a project generator for node.js, like yeoman but not as slow and hard to use.  Any interest in re-purposing this library into a project generator and collaborating on that, so we could use the `generate` name on npm?

**Comment by molnarg** [comment]
Hi Jon. This project has been unmaintained for a while, so I'm open to letting your project use this name. I've just unpublished the generate package on npm! Go ahead :)

**Comment by jonschlinkert** [comment]
Thanks! you're awesome!
